### ISSUE TITLE
DatePickerElement doesn't behave as the MUI one.

### ISSUE THREAD

**Issue by zkanda** [dohomi/react-hook-form-mui#113] opened 2023-01-13 03:17 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The date picker goes to top left.

<img width="524" alt="Screenshot 2023-01-13 at 10 14 14" src="https://user-images.githubusercontent.com/5354184/212228941-97cce153-4d0c-445e-80ff-2a7e6dd83baa.png">

And I also get a warning when opening this picker for the first time.

```
Warning: Failed prop type: MUI: The `anchorEl` prop provided to the component is invalid.
It should be an HTML element instance or a virtualElement 
(https://popper.js.org/docs/v2/virtual-elements/).
```

### Expected behavior 🤔

The expected behavior should be the same as MUI.

<img width="441" alt="Screenshot 2023-01-13 at 10 14 41" src="https://user-images.githubusercontent.com/5354184/212228972-ab074e03-000c-47fe-8558-bd2e951f1726.png">

### Steps to reproduce 🕹

Can be seen here.

https://stackblitz.com/edit/vitejs-vite-cc4enk?file=package.json

**Comment by dohomi** [comment] 2023-01-16 04:01
@zkanda this seems to be off. I use the picker on NextJS and Storybook without an issue please check https://react-hook-form-material-ui.vercel.app/?path=/story/datepickerelement--basic

I don't know what Vite or Stackblitz are doing different than my setup.

**Comment by AlexandrKostrov** [comment] 2023-01-16 22:20
Have the same issue

**Comment by roblav96** [comment] 2023-01-17 23:55
Same issue here as @zkanda

**Comment by FlorianCassayre** [comment] 2023-01-18 21:53
Same issue here. Actually I'm pretty sure it was working correctly in an earlier version but I can seem to find it.

**Comment by dohomi** [comment] 2023-01-19 00:57
Any PR is welcome, I can't see that issue in my environment and use this library in production without an issue so far.

**Comment by FlorianCassayre** [comment] 2023-01-19 10:00
Maybe it has to do with the version of React or MUI. Will check tonight.

**Comment by FlorianCassayre** [comment] 2023-01-22 11:00
Indeed, it was working properly on my side until I bumped `react-hook-form-mui` from version `5.7.2` to `5.12.3` (for reference, here is the [commit](https://github.com/FlorianCassayre/yoga-sof.fr/commit/fa5d7e9721fb81a1486a867754be18cea97bcbcf) that broke it in my project). Downgrading the library fixed it.

Bissecting on the versions of this package lead me to find that `5.12.0` is when the bug started appearing in my environment (between commits 7d2826b5b74b1ca7529dd5cd029c1bb42026e48f and a986ab368363fee8fb0e8e5252aad858c24fb8b4, included).

**Comment by FlorianCassayre** [comment] 2023-01-22 11:11
Alright, the problem was introduced in #109, namely the addition of:
```tsx
inputRef={ref}
```
That said I have no idea why it is working on some environments but not others.

**Comment by FlorianCassayre** [comment] 2023-01-22 11:28
Somehow relates to mui/material-ui-pickers#1768 but the proposed fix of using `ref={ref}` instead of `inputRef={ref}` breaks the intended feature regarding the focus. I'm not too familiar with this to be honest.

**Comment by dohomi** [comment] 2023-01-23 01:33
@FlorianCassayre could you elaborate why on Storyblok and NextJS there is no issue? I merged that PR back in the days and could not see any regression in my setup thats why I merged it. I am open to revert it. I am also not familiar with the focus ref myself

**Comment by FlorianCassayre** [comment] 2023-01-23 12:52
@dohomi I don't understand, actually. I am also using NextJS, that's where I am encountering the problem. May have to do with a peer dependency but this is just a guess.

I guess if this focus feature brings more harm than good, probably worth reverting it for the time being. I don't mind either way for now as I pinned the library to the latest working version in my project.

**Comment by dohomi** [comment] 2023-01-24 04:18
I reverted the changes of inputRef in v5.12.4, please let me know if that fixes the issue

**Comment by megasys1968** [comment] 2023-01-29 01:20
I was also encountering the same issue.
After updating to v5.12.4 the problem went away.
Thank you!

**Comment by dohomi** [comment] 2023-01-31 01:03
thanks @RubtsovAV I merged your PR. Will close this issue for now please open it again if 5.13.1 is causing any trouble

**Closed by dohomi** 2023-01-31 01:03 UTC
Labels: need feedback
