### ISSUE TITLE
Confused docs

### ISSUE THREAD

**Issue by Esmio** [dohomi/react-hook-form-mui#96] opened 2022-10-27 22:41 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello, this is the demo code of Date PIcker Component. I just got confused where does the _ and z come from?

### Examples 🌈

`
<DateFnsProvider>
  <_
    defaultValues={{}}
    onSuccess={function noRefCheck(){}}
  >
    <z
      label="Required Picker"
      name="requiredCustomMessage"
      required
      validation={{
        required: 'Custom required message'
      }}
    />
    <br />
    <SubmitButton />
  </_>
</DateFnsProvider>`

**Comment by dohomi** [comment] 2022-10-28 00:54
duplicate of #93

**Closed by dohomi** 2022-10-28 00:54 UTC
