### ISSUE TITLE
proposal-nullish-coalescing-operator compile error

### ISSUE THREAD

**Issue by wxsolo** [dohomi/react-hook-form-mui#78] opened 2022-07-25 13:07 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when I add loaders  plugins  @babel/plugin-proposal-nullish-coalescing-operator

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": { "version": 3, "proposals": true }
      }
    ]
  ],
  "plugins": ["@babel/plugin-proposal-nullish-coalescing-operator"]
}

```

but has this error

```
Failed to compile.

./node_modules/react-hook-form-mui/dist/esm/index.js 36:18
Module parse failed: Unexpected token (36:18)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       return e.createElement(v, { ...a,
|         name: i,
>         value: s ?? "",
|         onChange: m,
|         onBlur: C,
```

### Expected behavior 🤔

how to fix this "proposal-nullish-coalescing-operator" error

### Steps to reproduce 🕹

Steps:

1. 
2.
3.
4.

**Comment by dohomi** [comment] 2022-07-28 04:04
@wxsolo this never been an issue before and not everyone seems to use that particular babel plugin. Pleases provide a PR which fixes the issue thanks

**Comment by dohomi** [comment] 2022-07-28 04:04
@wxsolo this never been an issue before and not everyone seems to use that particular babel plugin. Pleases provide a PR which fixes the issue thanks

**Comment by sjdemartini** [comment] 2022-08-24 18:57
I tried installing and using this package within my app that used `create-react-app` but ran into the same `Failed to compile` error as the above, so I'm unable to use the package. That nullish coalescing operator babel plugin is used by default in CRA (see [here](https://github.com/facebook/create-react-app/blob/221e511730ca51c036c6954a9d2ee7659ff860f9/packages/babel-preset-react-app/package.json#L27)). Presumably this package's build needs to be compatible with that to ensure it can be used with apps created using create-react-app, though I'm not familiar with the details of this.

**Comment by jamiedruce** [comment] 2022-10-06 14:12
Anyone figure out a solution/workaround to this? Have the same problem as @sjdemartini in that we use CRA and get this error thrown.

Gone down a rabbit hole of Github issues with browser targeting tweaks etc but nothing seems to resolve it.

**Comment by dohomi** [comment] 2022-10-07 02:10
A repo which reproduce this issue would help. I am using this repo in 5+ production repos, all across NextJS, Storybook and Vite with React 17 and 18. Would be great if someone who faces this issue could wire up a reproduction and provide a PR or some insights about it.

**Comment by jamiedruce** [comment] 2022-10-07 13:02
FYI i'm looking to reproduce this in isolation. Interestingly I have made a basic codesandbox that works, but when ran locally, generates the error. So might be a local thing.

Will keep digging to see if I can find the root cause and why this package is the one that throws the error.

**Comment by jamiedruce** [comment] 2022-10-07 14:09
OK, i've made some progress!

In my instance, i've isolated it to be related to using esbuild with react-scripts v4.0.3, in my testing, it can be resolved by either:
1. Removing esbuild and using default CRA's webpack
2. Upgrading react-scripts to v5.0.1

Proved difficult to reproduce in a sandbox, but seems something was fixed in CRA in the latest version to help with this.

**Comment by dohomi** [comment] 2022-10-07 14:52
good to hear, I havent used CRA for long time (all my codebases are usually NextJS, Storybook or ViteJS).. glad it is resolved in latest CRA

**Closed** 2023-01-31 01:05 UTC
Labels: need feedback
